version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo_container
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0"]
    volumes:
      - ./mongo_data:/data/db
